### ISSUE TITLE
 Published-Papers Page

### ISSUE THREAD

**Issue by Madhav-Murali-NITC** [mikasajaeger19/SE_LAB_Team8_NITCONF#7]
- [x] Set up a table that calls the papers uploaded by the author from the databse and display it with information regarding each paper  in the form of a table 
- [ ]  Buttons to reupload papers,view comments, and view older versions of specific papers

Information in Table : 

1. Paper name
2. Author / Co-authors
3. Tags
4. Version
5. Status
6. Link to comments for the paper

**Comment by mikasajaeger19** [comment]
paper dashboard with details completed
